# Site settings
title: Esben Petersen
header-img: img/home-bg.jpg
email: esbenspetersen@gmail.com
description: "Young entrepreneur and business student. Writing B2B SaaS at Traede.com"
baseurl: ""
url: "http://esbenp.github.io"
twitter_username: esbenp
github_username:  esbenp
facebook_username:  esbenspetersen
timezone: Europe/Copenhagen

# Build settings
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

kramdown:
  input: GFM

gems: [jekyll-paginate]
